version: '3.3'
services:
    postgres:
        container_name: postgres
        environment:
            - POSTGRES_DB=majoo
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - PGDATA=/var/lib/postgresql/data/pgdata
        image: postgres
        restart: unless-stopped
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"